import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <h1
        style={{
          margin: "100px",
          width: "100px",
          height: "100px",
          backgroundColor: "red",
        }}
      >
        auth
      </h1>
      {children}
    </div>
  );
}
