// layout params
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1
          style={{
            margin: "100px",
            width: "100px",
            height: "100px",
            backgroundColor: "blue",
          }}
        >
          lt
        </h1>
        <Suspense fallback={<Loading/>}>{children}</Suspense>
      </body>
    </html>
  );
}
